Vagrant.configure("2") do |config|

  config.vm.define "static" do |static|
    static.vm.box = "jaca1805/debian12"

    static.vm.network "private_network", ip: "192.168.33.52"
  
    static.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end

  end

  config.vm.define "httpd" do |httpd|
    httpd.vm.box = "jaca1805/debian12"

    httpd.vm.network "private_network", ip: "192.168.33.53"
  
    httpd.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end

  end

  config.vm.define "postgres" do |postgres|
    postgres.vm.box = "jaca1805/debian12"

    postgres.vm.network "private_network", ip: "192.168.33.54"
  
    postgres.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end

  end

end
