Vagrant.configure("2") do |config|

  config.vm.define "static" do |static|
    static.vm.box = "jaca1805/debian12"

    static.vm.network "private_network", ip: "192.168.33.22"
  
    static.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end

  end

  config.vm.define "httpd" do |httpd|
    httpd.vm.box = "jaca1805/debian12"

    httpd.vm.network "private_network", ip: "192.168.33.23"
  
    httpd.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end

  end

  config.vm.define "db" do |db|
    db.vm.box = "jaca1805/debian12"

    db.vm.network "private_network", ip: "192.168.33.24"
  
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end

  end

end
